Resolve #5
gpsyrou/tube-virality pull request #8
Opened 2023-04-12 14:32 UTC by limiu82214

resolve #5 

I change the `.go` and create folder structure accroding this.  
[project-layout](https://github.com/golang-standards/project-layout) is famous folder structure.

I keep `src` folder because it contain file of python, in the feature I think that sould be delete after migrate code to golang.

2023-04-15 09:33 UTC, gpsyrou requested changes
This is great setup for the project thanks for the changes! One last  thing - Can we make a change so that **trending_run.py** updates the file **'trending_videos_metadata.csv'** in the newly created folder (i.e. assets/metadata/trending). It should be fairly easy change, just update the **trending_run.py** to point here `DATA_DIR_PATH = os.path.join(
    PROJECT_DIR_PATH, 'assets/metadata/trending'
    )`

2023-04-15 15:19 UTC, limiu82214 commented
Sure I change DIR and try to run `trending` with python3, and I fix a little fail.
BTW I add a makefile command `make make runPullTrending` and Update it to README

2023-04-22 14:49 UTC, gpsyrou approved these changes

2023-04-22 14:49 UTC, gpsyrou commented on src/tube/trending/trend.py
> +            df_trending_history = df_trending_history._append(
This will throw an error, needs to be `append` instead of `_append`

2023-04-22 14:51 UTC, merged